#global configs & defaults
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework: debug
